#!/usr/bin/env python3
"""Generate a domain campaign manifest (configs/campaign_if.tsv / campaign_code.tsv).

All stock arms x 3 seeds, machine `any` (the pool), EXCEPT:
  * vanilla's three seeds are PINNED to d0 -- the noise floor comes from one box
    (the m1 principle), and in a DLC pool nothing else would guarantee that;
  * a2_coldstart is fenced: its stage-1 SFT checkpoint is per-domain and does not
    exist yet -- running it would train math-SFT init on an IF/code stream, which
    answers no registered question.

Deterministic: the manifest is generated once and COMMITTED; this script exists
so the roster's provenance is reproducible, not so manifests get regenerated ad
hoc (they are the single source of dispatch, same discipline as campaign.tsv).

    python scripts/gen_domain_manifest.py if   > configs/campaign_if.tsv
    python scripts/gen_domain_manifest.py code > configs/campaign_code.tsv
"""
import sys

import yaml

DOMAIN = sys.argv[1] if len(sys.argv) > 1 else "if"
# The topology-carrying family pins NGPUS_PER_NODE=2 + TEACHER_WORLD_SIZE=2 in
# its arm env (4 GPUs total), and arm env lands AFTER namespace env -- on a
# 2-GPU domain lane these arms fail at boot, every attempt, three strikes each.
# They go to dedicated 4-GPU boxes (the worker seeds GPUS_PER_RUN.d{2,3,4}=4).
WIDE = ["b3_eopd_gate", "d1_tip", "d2_selectkd", "d3_teachability",
        "vanilla_n8", "j1_kdrl", "g2_fire_likelihood"]
WIDE_BOXES = ["d2", "d3", "d4"]

FENCED = {
    "a2_coldstart": "needs=/nonexistent/per-domain-sft-stage1 -- math SFT init on a "
                    "domain stream answers no registered question; unlock = build the "
                    "domain's own stage-1 and repoint arms.yaml, a pin move",
}

arms = yaml.safe_load(open("configs/arms.yaml"))["arms"]
stock = [a["run_id"] for a in arms if a.get("status") == "stock"]

print(f"# Domain campaign manifest: {DOMAIN}4k. Generated by scripts/gen_domain_manifest.py,")
print(f"# then COMMITTED -- this file, not the generator, is the source of dispatch.")
print(f"# Namespace: MANIFEST=configs/campaign_{DOMAIN}.tsv CLAIM_DIR=.campaign_{DOMAIN}")
print(f"# (BATCH_TAG={DOMAIN}4k lives in the claim dir; run names become <arm>_s<seed>_{DOMAIN}4k,")
print(f"# so checkpoints and fingerprints never collide with the math campaign's.)")
print(f"# Columns: wave machine arm seed [note] -- same schema as campaign.tsv.")
print()
print("# -- wave 1: the noise floor, one box on purpose ------------------------------")
for s in range(3):
    note = "\tthe three seeds ARE this domain's noise floor" if s == 2 else ""
    print(f"1\td0\tvanilla\t{s}{note}")
print()
print("# -- wave 1 pool: every other stock arm x 3 seeds -----------------------------")
for rid in stock:
    if rid == "vanilla":
        continue
    fence = FENCED.get(rid)
    for s in range(3):
        note = f"\t{fence}" if fence else ""
        if rid in WIDE:
            box = WIDE_BOXES[(WIDE.index(rid) * 3 + s) % len(WIDE_BOXES)]
            print(f"1\t{box}\t{rid}\t{s}\t4-GPU family; box width seeded by the worker{note and ' ' + fence}")
        else:
            print(f"1\tany\t{rid}\t{s}{note}")
