#!/usr/bin/env bash
# Stop everything, update, verify, launch, and confirm the lanes really started.
#
#   bash deploy/dsw/launch.sh
#   STEPS=150 RUNS="vanilla:0 vanilla:1" bash deploy/dsw/launch.sh
#   SKIP_PULL=1 bash deploy/dsw/launch.sh
#
# This is a full machine reset, so `ray stop --force` is the right tool here -- it is
# only off limits inside a lane, where it would take the other three down with it.
#
# On skipping the rehearsal: the one thing it would have caught is the three sweep
# nets interfering across four concurrent lanes, which has never been exercised. Each
# net is verified on its own (process group under a tty-less nohup, anchored pkill
# against a lane1/lane10 pair, nvidia-smi -i confirmed to ignore CUDA_VISIBLE_DEVICES
# on an A100 node), so what is untested is their interaction. Step 6 below recovers
# most of that for free: it watches until every lane has passed startup and reached a
# real training step, which is exactly where lane interference shows up. If a lane is
# going to be strangled by another lane's cleanup, it happens there, not at hour 12.

set -uo pipefail
SIMOPD_ROOT=${SIMOPD_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}
cd "$SIMOPD_ROOT"

STEPS=${STEPS:-250}
RUNS=${RUNS:-"vanilla:0 vanilla:1 vanilla:2 f1_soft_log:0"}
STARTUP_WAIT=${STARTUP_WAIT:-1800}     # seconds to wait for every lane to reach step 1

say() { printf '\n\033[1m=== %s\033[0m\n' "$1"; }

say "1/6  stopping everything"
# Bracketed so the pattern cannot match this script's own command line.
pkill -f "[_]lane.sh"            2>/dev/null && echo "  killed lane workers"
pkill -f "[r]un_opd_baseline.sh" 2>/dev/null && echo "  killed run scripts"
pkill -f "[v]erl.trainer.main_ppo" 2>/dev/null && echo "  killed trainers"
ray stop --force >/dev/null 2>&1 && echo "  ray stopped"
sleep 5
_left=$(nvidia-smi --query-compute-apps=pid --format=csv,noheader 2>/dev/null | wc -l)
echo "  GPU compute processes remaining: $_left"
if [ "$_left" -gt 0 ]; then
    echo "  still occupied -- these survived:" >&2
    nvidia-smi --query-compute-apps=pid,used_memory --format=csv 2>/dev/null | sed 's/^/    /' >&2
    echo "  kill them by hand before launching, or the lanes will fight them for memory" >&2
    exit 1
fi

say "2/6  updating"
if [ "${SKIP_PULL:-0}" = 1 ]; then
    echo "  skipped (SKIP_PULL=1), at $(git rev-parse --short HEAD)"
elif ! git pull --ff-only; then
    echo "  git pull failed -- resolve it first; launching stale code is worse than waiting." >&2
    echo "  (local edits? git stash, or SKIP_PULL=1 if they are deliberate)" >&2
    exit 1
fi

say "3/6  environment"
# simopd_env.sh is generated by setup.sh and is not in git, so a pull does not update
# it. That matters: run_parallel.sh falls back to ${VLLM_USE_MODELSCOPE:-False}, and
# `:-` does NOT override a value the image already exported -- only a regenerated
# simopd_env.sh, sourced first, actually wins that argument.
if ! grep -qs "VLLM_USE_MODELSCOPE" simopd_env.sh; then
    echo "  simopd_env.sh predates the vLLM ModelScope flag -- regenerating (idempotent)"
    VERL_USE_MODELSCOPE=${VERL_USE_MODELSCOPE:-False} \
    VLLM_USE_MODELSCOPE=${VLLM_USE_MODELSCOPE:-False} \
        bash deploy/dsw/setup.sh || { echo "  setup failed" >&2; exit 1; }
else
    echo "  simopd_env.sh is current"
fi
# shellcheck disable=SC1091
source simopd_env.sh
for v in VERL_USE_MODELSCOPE VLLM_USE_MODELSCOPE; do
    printf '  %s=%s\n' "$v" "$(eval echo "\${$v:-<unset>}")"
    case "$(eval echo "\${$v:-False}" | tr '[:upper:]' '[:lower:]')" in
        true|1|yes) echo "  NOTE: $v is on; models resolve through ModelScope and" >&2
                    echo "        fetch_assets.py checks that cache. Consistent, but deliberate?" >&2 ;;
    esac
done

say "4/6  health"
bash deploy/dsw/doctor.sh || true      # advisory; run_parallel.sh has the hard gate
_runs=$(set -- $RUNS; echo $#)
_need=$(( _runs * ${MAX_CKPT_KEEP:-2} * 29 ))    # ~25GB shards + ~3.4GB hf_model
_free=$(df -BG --output=avail "${CKPT_ROOT:-.}" 2>/dev/null | tail -1 | tr -dc '0-9')
echo "  disk: ${_free:-?}G free, ~${_need}G needed for $_runs runs"

say "5/6  launching  ($_runs runs, $STEPS steps)"
STEPS="$STEPS" bash deploy/dsw/run_parallel.sh "$RUNS" || {
    echo "  launch refused -- see the pre-flight message above; nothing is running." >&2
    exit 1
}

say "6/6  confirming every lane got past startup"
# The rehearsal's real job, folded in. A lane that is going to be killed by a
# neighbour's cleanup dies during startup, when Ray and vLLM are coming up -- so
# waiting for all four to report a training step is the check that matters.
deadline=$(( $(date +%s) + STARTUP_WAIT ))
newest=$(ls -t "$SIMOPD_ROOT"/logs/lane*.log 2>/dev/null | head -1)
stamp=${newest##*_}; stamp=${stamp%.log}
while :; do
    logs=$(ls "$SIMOPD_ROOT"/logs/lane*_*.log 2>/dev/null | tail -4)
    started=0; total=0
    for l in $logs; do
        total=$((total + 1))
        grep -qE "Training Progress:.*\| *[1-9]" "$l" 2>/dev/null && started=$((started + 1))
    done
    now=$(date +%s)
    printf '\r  %d/%d lanes at step >=1   (%ds left)   ' "$started" "$total" "$((deadline - now))"
    [ "$total" -gt 0 ] && [ "$started" -eq "$total" ] && { echo; break; }
    [ "$now" -ge "$deadline" ] && { echo; echo "  TIMEOUT: only $started/$total lanes started." >&2
        echo "  python scripts/triage.py --ray     # the ones that did not" >&2; exit 1; }
    # a lane whose process is gone will never start; fail fast instead of waiting out the clock
    if ! pgrep -f "[_]lane.sh" >/dev/null 2>&1; then
        echo; echo "  every lane process has exited already -- that is a failure, not a finish." >&2
        echo "  python scripts/triage.py --ray" >&2; exit 1
    fi
    sleep 30
done

echo "  all lanes training."
cat <<EOF

  watch:    python scripts/watch.py --watch 300
  enforce:  python scripts/watch.py --watch 300 --enforce
  triage:   python scripts/triage.py --ray
  logs:     $SIMOPD_ROOT/logs/lane*_${stamp}.log
EOF
